import Head from "next/head";
import Form from "./Form";

export default function Layout({ title = "Form" }) {

  return (
    <div>

      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Form />

    </div>

  );
}
